<?php
/**
 * Public AI discovery files.
 *
 * @package WP_AI_OS
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

require_once WP_AI_OS_PATH . 'includes/class-settings.php';

class WP_AI_OS_Public_AI_Files {

	public function __construct() {
		add_action( 'init', array( $this, 'add_rewrite_rule' ) );
		add_filter( 'query_vars', array( $this, 'query_vars' ) );
		add_action( 'template_redirect', array( $this, 'render' ) );
	}

	public function add_rewrite_rule(): void {
		add_rewrite_rule( '^llms\.txt$', 'index.php?wp_ai_os_llms=1', 'top' );
	}

	public function query_vars( array $vars ): array {
		$vars[] = 'wp_ai_os_llms';
		return $vars;
	}

	public function render(): void {
		if ( '1' !== (string) get_query_var( 'wp_ai_os_llms' ) || ! WP_AI_OS_Settings::get( 'enable_llms_txt', true ) ) {
			return;
		}

		header( 'Content-Type: text/plain; charset=' . get_bloginfo( 'charset' ) );
		header( 'X-Robots-Tag: noindex' );

		$name = (string) WP_AI_OS_Settings::get( 'organization_name', get_bloginfo( 'name' ) );
		$url  = (string) WP_AI_OS_Settings::get( 'organization_url', home_url( '/' ) );

		echo '# ' . sanitize_text_field( $name ) . "\n\n";
		echo '> AI-readable site profile generated by WP AI OS.\n\n';
		echo 'Site: ' . esc_url_raw( $url ) . "\n";
		echo 'Language: ' . esc_html( get_bloginfo( 'language' ) ) . "\n\n";
		echo '## Important URLs\n\n';
		echo '- Homepage: ' . esc_url_raw( home_url( '/' ) ) . "\n";
		echo '- Sitemap: ' . esc_url_raw( home_url( '/wp-sitemap.xml' ) ) . "\n";
		echo '- REST API: ' . esc_url_raw( rest_url() ) . "\n";
		echo "\n## Content\n\n";
		echo '- Posts: ' . absint( wp_count_posts( 'post' )->publish ?? 0 ) . " published\n";
		echo '- Pages: ' . absint( wp_count_posts( 'page' )->publish ?? 0 ) . " published\n";

	exit;
	}
}
